### ISSUE TITLE
wasm-build renames substrate 'deploy' export

### ISSUE THREAD

**Issue by holygits** [paritytech/wasm-utils#108]
https://github.com/paritytech/wasm-utils/blob/24b97b517abd8419ddf1551fddac671c616797ed/src/pack.rs#L203-L205

This causes it to fail a deploy time check in Substrate:
https://github.com/paritytech/substrate/blob/4f993e6ac8f55cfe8d035ecb95fa5e4d1cf34b8b/srml/contract/src/wasm/prepare.rs#L181-L183

I'm not sure on the intended behaviour here so this issue may need to be moved to the substrate repo. accordingly

**Comment by fckt** [comment]
It's just a way we do pack binary on [`pwasm`](https://github.com/paritytech/pwasm-tutorial#building). Isn't packing for Substrate must be different?
@pepyakin

**Comment by holygits** [comment]
Opened a PR to fix the issue here if needed
