### ISSUE TITLE
Update crates.io version

### ISSUE THREAD

**Issue by holygits** [paritytech/wasm-utils#117]
The `wasm-build` in this package on crates.io seems to have regressed the fixes in #109

i.e. this version still strips 'deploy' symbol
```
cargo install pwasm-utils-cli --bin wasm-build
```

While the repo master is ok
```
cargo install pwasm-utils-cli --bin wasm-build --git https://github.com/paritytech/wasm-utils
```

**Comment by NikVolf** [comment]
0.7 out!
