### ISSUE TITLE
wasm-opt name collision with binaryen

### ISSUE THREAD

**Issue by pchickey** [paritytech/wasm-utils#15]
I would like to use the `wasm-opt` tool, which seems quite useful, but it has the same name as another useful tool from https://github.com/webassembly/binaryen. Would you be open to renaming your tool so that both can co-exist in the same PATH?

**Comment by NikVolf** [comment]
Sure, can you think of any cool name though? ;)

**Comment by pchickey** [comment]
At the moment the operation exposed by the tool could be described as "tree pruning" (perhaps not completely accurate) or "tree-shaking" (a smalltalk-ism a colleague suggested). Linkers sometimes call this pass "garbage collection", but that is a broad term with many uses elsewhere.

@silentbicycle suggested "cellulose" since its related to trees and losing cells, or "swail" which is a word for a controlled burn in forestry.

My vote is for `wasm-prune` but I am not picky.
